
info="""
Test experiment config. Sweep over gamma with 10 seeds.
"""

[config]
save_backend="file" # file saving mode
file_type = "jld2" # using JLD2 as save type
save_dir="test_experiment" # save location
exp_file = "experiments/TestExperiment.jl"
exp_module_name = "TestExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps = 50
learning_update = "QLearning"

[sweep_args]
# Put args to sweep over here.
seed = "1:10"
gamma = "0.0:0.1:0.9"

